# Generated by Django 5.2.3 on 2025-06-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House_prices",
            fields=[
                ("Date", models.DateField(primary_key=True, serialize=False)),
                ("Region_Name", models.CharField(max_length=100)),
                ("Area_Code", models.CharField(max_length=10)),
                (
                    "Detached_Average_Price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Detached_Index",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Detached_Monthly_Change",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Detached_Annual_Change",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Semi_Detached_Average_Price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Semi_Detached_Index",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Semi_Detached_Monthly_Change",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Semi_Detached_Annual_Change",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Terraced_Average_Price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Terraced_Index",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Terraced_Monthly_Change",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Terraced_Annual_Change",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Flat_Average_Price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Flat_Index",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Flat_Monthly_Change",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                (
                    "Flat_Annual_Change",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
