# Generated by Django 5.2.3 on 2025-06-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="house_prices",
            options={"ordering": ("Date",)},
        ),
    ]
