# Generated by Django 5.2.3 on 2025-06-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0002_alter_house_prices_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="house_prices",
            options={},
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Area_Code",
            new_name="area_code",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Detached_Annual_Change",
            new_name="detached_annual_change",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Detached_Average_Price",
            new_name="detached_average_price",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Detached_Index",
            new_name="detached_index",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Detached_Monthly_Change",
            new_name="detached_monthly_change",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Flat_Annual_Change",
            new_name="flat_annual_change",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Flat_Average_Price",
            new_name="flat_average_price",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Flat_Index",
            new_name="flat_index",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Flat_Monthly_Change",
            new_name="flat_monthly_change",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Region_Name",
            new_name="region_name",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Semi_Detached_Annual_Change",
            new_name="semi_detached_annual_change",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Semi_Detached_Average_Price",
            new_name="semi_detached_average_price",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Semi_Detached_Index",
            new_name="semi_detached_index",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Semi_Detached_Monthly_Change",
            new_name="semi_detached_monthly_change",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Terraced_Annual_Change",
            new_name="terraced_annual_change",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Terraced_Average_Price",
            new_name="terraced_average_price",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Terraced_Index",
            new_name="terraced_index",
        ),
        migrations.RenameField(
            model_name="house_prices",
            old_name="Terraced_Monthly_Change",
            new_name="terraced_monthly_change",
        ),
    ]
