# Generated by Django 5.2.3 on 2025-06-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0003_alter_house_prices_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="house_prices",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="date",
            field=models.DateField(),
        ),
    ]
