# Generated by Django 5.2.3 on 2025-06-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0004_house_prices_id_alter_house_prices_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="House_prices",
            new_name="Property_Prices",
        ),
    ]
