# Generated by Django 5.2.3 on 2025-06-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0005_rename_house_prices_property_prices"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Property_Prices",
            new_name="House_Prices",
        ),
    ]
