# Generated by Django 5.2.3 on 2025-06-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0006_rename_property_prices_house_prices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house_prices",
            name="area_code",
        ),
    ]
