# Generated by Django 5.2.3 on 2025-06-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0007_remove_house_prices_area_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house_prices",
            name="detached_annual_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="detached_average_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="detached_index",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="detached_monthly_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="flat_annual_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="flat_average_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="flat_index",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="flat_monthly_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="semi_detached_annual_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="semi_detached_average_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="semi_detached_index",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="semi_detached_monthly_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="terraced_annual_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="terraced_average_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="terraced_index",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house_prices",
            name="terraced_monthly_change",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
