# # Comments are provided throughout this file to help you get started.
# # If you need more help, visit the Docker Compose reference guide at
# # https://docs.docker.com/go/compose-spec-reference/

# # Here the instructions define your application as a service called "server".
# # This service is built from the Dockerfile in the current directory.
# # You can add other services your application may depend on here, such as a
# # database or a cache. For examples, see the Awesome Compose repository:
# # https://github.com/docker/awesome-compose
# services:
#   django:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ./backend:/backend
#     ports:
#       - "8000:8000"
#     depends_on:
#       - metabase
#     command: python manage.py runserver 0.0.0.0:8000
#     # venv_file:
#     #   - .venv
  
#   metabase:
#     image: metabase/metabase
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./metabase-data:/metabase-data
#     environment:
#       MB_DB_FILE: /metabase-data/metabase.db

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase.db
      - ./backend/db.sqlite3:/data/db.sqlite3
    environment:
      - MB_DB_FILE=/metabase.db/metabase.db



